-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:0410babea970c42a023fc2c0e6919de9:43e1cc02bea15532b67715e67ae43e75:7d92f79d2a9496e044cb657a08b4cd08$
-- 

return {
	texture = 'bum2.png',
	frames = {
			{
				name = "idle/Bum20000",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 54 },
				uvRect = { u0 = 0.00806452, v0 = 0.0344828, u1 = 0.165323, v1 = 0.965517 },
				spriteSourceSize = { width = 39, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "walk/Bum20000",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 54 },
				uvRect = { u0 = 0.00806452, v0 = 0.0344828, u1 = 0.165323, v1 = 0.965517 },
				spriteSourceSize = { width = 39, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "walk/Bum20001",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 54 },
				uvRect = { u0 = 0.173387, v0 = 0.0344828, u1 = 0.330645, v1 = 0.965517 },
				spriteSourceSize = { width = 39, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "walk/Bum20002",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 54 },
				uvRect = { u0 = 0.33871, v0 = 0.0344828, u1 = 0.495968, v1 = 0.965517 },
				spriteSourceSize = { width = 39, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "walk/Bum20003",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 54 },
				uvRect = { u0 = 0.504032, v0 = 0.0344828, u1 = 0.66129, v1 = 0.965517 },
				spriteSourceSize = { width = 39, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "walk/Bum20004",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 54 },
				uvRect = { u0 = 0.669355, v0 = 0.0344828, u1 = 0.826613, v1 = 0.965517 },
				spriteSourceSize = { width = 39, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "walk/Bum20005",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 54 },
				uvRect = { u0 = 0.834677, v0 = 0.0344828, u1 = 0.991935, v1 = 0.965517 },
				spriteSourceSize = { width = 39, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

