-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:3365d24d906e099c3cdfdc3908db376f:32b1fb4af1ceffb49693e716ab96c271:a0b64c4771ca06039bb6f0e68194b35f$
-- 

return {
	texture = 'bum3.png',
	frames = {
			{
				name = "idle/Bum30000",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 54 },
				uvRect = { u0 = 0.00787402, v0 = 0.0344828, u1 = 0.165354, v1 = 0.965517 },
				spriteSourceSize = { width = 40, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "walk/Bum30000",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 54 },
				uvRect = { u0 = 0.00787402, v0 = 0.0344828, u1 = 0.165354, v1 = 0.965517 },
				spriteSourceSize = { width = 40, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "walk/Bum30001",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 54 },
				uvRect = { u0 = 0.173228, v0 = 0.0344828, u1 = 0.330709, v1 = 0.965517 },
				spriteSourceSize = { width = 40, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "walk/Bum30002",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 54 },
				uvRect = { u0 = 0.338583, v0 = 0.0344828, u1 = 0.496063, v1 = 0.965517 },
				spriteSourceSize = { width = 40, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "walk/Bum30003",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 54 },
				uvRect = { u0 = 0.503937, v0 = 0.0344828, u1 = 0.661417, v1 = 0.965517 },
				spriteSourceSize = { width = 40, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "walk/Bum30004",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 54 },
				uvRect = { u0 = 0.669291, v0 = 0.0344828, u1 = 0.826772, v1 = 0.965517 },
				spriteSourceSize = { width = 40, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "walk/Bum30005",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 54 },
				uvRect = { u0 = 0.834646, v0 = 0.0344828, u1 = 0.992126, v1 = 0.965517 },
				spriteSourceSize = { width = 40, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

