-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:3172c454ff044ab33e27876eded0e733:d0e70cf18673439f46e5917f1015d3a5:aab4dbf1c8e8ef502d7f0b5f217bc0df$
-- 

return {
	texture = 'gascan.png',
	frames = {
			{
				name = "idle/gascan",
				spriteColorRect = { x = 0, y = 0, width = 22, height = 29 },
				uvRect = { u0 = 0.0769231, v0 = 0.0606061, u1 = 0.923077, v1 = 0.939394 },
				spriteSourceSize = { width = 22, height = 29 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

