-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:dc84314edca0836b6e33e9db50fdc0f9:01bd3a5296f8aa009765c4d0309fc37c:9a88d5d8e6885bbe12e13925e72ea81c$
-- 

return {
	texture = 'ninja.png',
	frames = {
			{
				name = "flip/Ninja0001",
				spriteColorRect = { x = 0, y = 0, width = 56, height = 64 },
				uvRect = { u0 = 0.0333333, v0 = 0.00431034, u1 = 0.966667, v1 = 0.142241 },
				spriteSourceSize = { width = 56, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "flip/Ninja0002",
				spriteColorRect = { x = 0, y = 0, width = 56, height = 64 },
				uvRect = { u0 = 0.0333333, v0 = 0.146552, u1 = 0.966667, v1 = 0.284483 },
				spriteSourceSize = { width = 56, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "flip/Ninja0003",
				spriteColorRect = { x = 0, y = 0, width = 56, height = 64 },
				uvRect = { u0 = 0.0333333, v0 = 0.288793, u1 = 0.966667, v1 = 0.426724 },
				spriteSourceSize = { width = 56, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "flip/Ninja0004",
				spriteColorRect = { x = 0, y = 0, width = 56, height = 64 },
				uvRect = { u0 = 0.0333333, v0 = 0.431034, u1 = 0.966667, v1 = 0.568965 },
				spriteSourceSize = { width = 56, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "flip/Ninja0005",
				spriteColorRect = { x = 0, y = 0, width = 56, height = 64 },
				uvRect = { u0 = 0.0333333, v0 = 0.573276, u1 = 0.966667, v1 = 0.711207 },
				spriteSourceSize = { width = 56, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "flip/Ninja0006",
				spriteColorRect = { x = 0, y = 0, width = 56, height = 64 },
				uvRect = { u0 = 0.0333333, v0 = 0.715517, u1 = 0.966667, v1 = 0.853448 },
				spriteSourceSize = { width = 56, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "flip/Ninja0007",
				spriteColorRect = { x = 0, y = 0, width = 56, height = 64 },
				uvRect = { u0 = 0.0333333, v0 = 0.857759, u1 = 0.966667, v1 = 0.99569 },
				spriteSourceSize = { width = 56, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "idle/Ninja0000",
				spriteColorRect = { x = 0, y = 0, width = 56, height = 64 },
				uvRect = { u0 = 0.0333333, v0 = 0.857759, u1 = 0.966667, v1 = 0.99569 },
				spriteSourceSize = { width = 56, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

