-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:928f7064deba21f6a6ada5c34b00b110:e63569817150ce2520cba791fd56667b:58f5656dd11de835ae63e2414f41681f$
-- 

return {
	texture = 'ninjastar.png',
	frames = {
			{
				name = "Shuruken1.png",
				spriteColorRect = { x = 0, y = 0, width = 25, height = 25 },
				uvRect = { u0 = 0.517857, v0 = 0.0689655, u1 = 0.964286, v1 = 0.931035 },
				spriteSourceSize = { width = 25, height = 25 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Shuruken2.png",
				spriteColorRect = { x = 0, y = 0, width = 25, height = 25 },
				uvRect = { u0 = 0.0357143, v0 = 0.0689655, u1 = 0.482143, v1 = 0.931035 },
				spriteSourceSize = { width = 25, height = 25 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

