-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:dd067a3d94c3977c4d28f4d65fcf936e:a9c4ca29ce904b873007a40722defca1:20bf4e8970b1a994f2650b72041123f0$
-- 

return {
	texture = 'ninjastar.png',
	frames = {
			{
				name = "diagleft/Kornpop0001",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 19 },
				uvRect = { u0 = 0.0196078, v0 = 0.0869565, u1 = 0.245098, v1 = 0.913043 },
				spriteSourceSize = { width = 23, height = 19 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "diagright/Kornpop0003",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 19 },
				uvRect = { u0 = 0.264706, v0 = 0.0869565, u1 = 0.490196, v1 = 0.913043 },
				spriteSourceSize = { width = 23, height = 19 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "horizontal/Kornpop0000",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 19 },
				uvRect = { u0 = 0.509804, v0 = 0.0869565, u1 = 0.735294, v1 = 0.913043 },
				spriteSourceSize = { width = 23, height = 19 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "vertical/Kornpop0002",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 19 },
				uvRect = { u0 = 0.754902, v0 = 0.0869565, u1 = 0.980392, v1 = 0.913043 },
				spriteSourceSize = { width = 23, height = 19 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

