-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:0f6cd5ab4ddf67e5e47c4b0b4316f6f4:daed8817afa18af6ea8a5486002d8450:e9cf3092fc75345d9899fd0df4d99139$
-- 

return {
	texture = 'pc.png',
	frames = {
			{
				name = "EE/LegsEE0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.00182815, v0 = 0.00425532, u1 = 0.047532, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "EE/LegsEE0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.0493601, v0 = 0.00425532, u1 = 0.095064, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "EE/LegsEE0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.0968921, v0 = 0.00425532, u1 = 0.142596, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "EE/LegsEE0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.144424, v0 = 0.00425532, u1 = 0.190128, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "EE/LegsEE0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.191956, v0 = 0.00425532, u1 = 0.23766, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "EE/LegsEE0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.239488, v0 = 0.00425532, u1 = 0.285192, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "EN/LegsES0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.28702, v0 = 0.00425532, u1 = 0.332724, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "EN/LegsES0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.334552, v0 = 0.00425532, u1 = 0.380256, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "EN/LegsES0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.382084, v0 = 0.00425532, u1 = 0.427788, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "EN/LegsES0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.429616, v0 = 0.00425532, u1 = 0.47532, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "EN/LegsES0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.477148, v0 = 0.00425532, u1 = 0.522852, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "EN/LegsES0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.52468, v0 = 0.00425532, u1 = 0.570384, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ES/LegsES0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.28702, v0 = 0.00425532, u1 = 0.332724, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ES/LegsES0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.334552, v0 = 0.00425532, u1 = 0.380256, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ES/LegsES0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.382084, v0 = 0.00425532, u1 = 0.427788, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ES/LegsES0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.429616, v0 = 0.00425532, u1 = 0.47532, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ES/LegsES0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.477148, v0 = 0.00425532, u1 = 0.522852, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ES/LegsES0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.52468, v0 = 0.00425532, u1 = 0.570384, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "EW/LegsWW0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.572212, v0 = 0.00425532, u1 = 0.617916, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "EW/LegsWW0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.619744, v0 = 0.00425532, u1 = 0.665448, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "EW/LegsWW0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.667276, v0 = 0.00425532, u1 = 0.71298, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "EW/LegsWW0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.714808, v0 = 0.00425532, u1 = 0.760512, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "EW/LegsWW0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.76234, v0 = 0.00425532, u1 = 0.808044, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "EW/LegsWW0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.809872, v0 = 0.00425532, u1 = 0.855576, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NE/LegsNE0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.857404, v0 = 0.00425532, u1 = 0.903108, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NE/LegsNE0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.904936, v0 = 0.00425532, u1 = 0.95064, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NE/LegsNE0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.952468, v0 = 0.00425532, u1 = 0.998172, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NE/LegsNE0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.00182815, v0 = 0.114894, u1 = 0.047532, v1 = 0.221277 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NE/LegsNE0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.0493601, v0 = 0.114894, u1 = 0.095064, v1 = 0.221277 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NE/LegsNE0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.0968921, v0 = 0.114894, u1 = 0.142596, v1 = 0.221277 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NEE/LegsNEE0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.144424, v0 = 0.114894, u1 = 0.190128, v1 = 0.221277 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NEE/LegsNEE0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.191956, v0 = 0.114894, u1 = 0.23766, v1 = 0.221277 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NEE/LegsNEE0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.239488, v0 = 0.114894, u1 = 0.285192, v1 = 0.221277 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NEE/LegsNEE0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.28702, v0 = 0.114894, u1 = 0.332724, v1 = 0.221277 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NEE/LegsNEE0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.334552, v0 = 0.114894, u1 = 0.380256, v1 = 0.221277 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NEE/LegsNEE0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.382084, v0 = 0.114894, u1 = 0.427788, v1 = 0.221277 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NEN/LegsNEN0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.429616, v0 = 0.114894, u1 = 0.47532, v1 = 0.221277 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NEN/LegsNEN0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.477148, v0 = 0.114894, u1 = 0.522852, v1 = 0.221277 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NEN/LegsNEN0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.52468, v0 = 0.114894, u1 = 0.570384, v1 = 0.221277 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NEN/LegsNEN0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.572212, v0 = 0.114894, u1 = 0.617916, v1 = 0.221277 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NEN/LegsNEN0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.619744, v0 = 0.114894, u1 = 0.665448, v1 = 0.221277 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NEN/LegsNEN0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.667276, v0 = 0.114894, u1 = 0.71298, v1 = 0.221277 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NES/LegsNES0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.714808, v0 = 0.114894, u1 = 0.760512, v1 = 0.221277 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NES/LegsNES0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.76234, v0 = 0.114894, u1 = 0.808044, v1 = 0.221277 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NES/LegsNES0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.809872, v0 = 0.114894, u1 = 0.855576, v1 = 0.221277 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NES/LegsNES0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.857404, v0 = 0.114894, u1 = 0.903108, v1 = 0.221277 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NES/LegsNES0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.904936, v0 = 0.114894, u1 = 0.95064, v1 = 0.221277 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NES/LegsNES0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.952468, v0 = 0.114894, u1 = 0.998172, v1 = 0.221277 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NEW/LegsNEW0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.00182815, v0 = 0.225532, u1 = 0.047532, v1 = 0.331915 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NEW/LegsNEW0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.0493601, v0 = 0.225532, u1 = 0.095064, v1 = 0.331915 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NEW/LegsNEW0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.0968921, v0 = 0.225532, u1 = 0.142596, v1 = 0.331915 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NEW/LegsNEW0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.144424, v0 = 0.225532, u1 = 0.190128, v1 = 0.331915 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NEW/LegsNEW0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.191956, v0 = 0.225532, u1 = 0.23766, v1 = 0.331915 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NEW/LegsNEW0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.239488, v0 = 0.225532, u1 = 0.285192, v1 = 0.331915 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NN/LegsNN0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.28702, v0 = 0.225532, u1 = 0.332724, v1 = 0.331915 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NN/LegsNN0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.334552, v0 = 0.225532, u1 = 0.380256, v1 = 0.331915 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NN/LegsNN0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.382084, v0 = 0.225532, u1 = 0.427788, v1 = 0.331915 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NN/LegsNN0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.429616, v0 = 0.225532, u1 = 0.47532, v1 = 0.331915 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NN/LegsNN0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.477148, v0 = 0.225532, u1 = 0.522852, v1 = 0.331915 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NN/LegsNN0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.52468, v0 = 0.225532, u1 = 0.570384, v1 = 0.331915 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NS/LegsNS0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.572212, v0 = 0.225532, u1 = 0.617916, v1 = 0.331915 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NS/LegsNS0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.619744, v0 = 0.225532, u1 = 0.665448, v1 = 0.331915 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NS/LegsNS0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.667276, v0 = 0.225532, u1 = 0.71298, v1 = 0.331915 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NS/LegsNS0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.714808, v0 = 0.225532, u1 = 0.760512, v1 = 0.331915 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NS/LegsNS0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.76234, v0 = 0.225532, u1 = 0.808044, v1 = 0.331915 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NS/LegsNS0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.809872, v0 = 0.225532, u1 = 0.855576, v1 = 0.331915 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NW/LegsNW0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.857404, v0 = 0.225532, u1 = 0.903108, v1 = 0.331915 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NW/LegsNW0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.904936, v0 = 0.225532, u1 = 0.95064, v1 = 0.331915 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NW/LegsNW0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.952468, v0 = 0.225532, u1 = 0.998172, v1 = 0.331915 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NW/LegsNW0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.00182815, v0 = 0.33617, u1 = 0.047532, v1 = 0.442553 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NW/LegsNW0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.0493601, v0 = 0.33617, u1 = 0.095064, v1 = 0.442553 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NW/LegsNW0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.0968921, v0 = 0.33617, u1 = 0.142596, v1 = 0.442553 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NWE/LegsNWE0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.144424, v0 = 0.33617, u1 = 0.190128, v1 = 0.442553 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NWE/LegsNWE0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.191956, v0 = 0.33617, u1 = 0.23766, v1 = 0.442553 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NWE/LegsNWE0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.239488, v0 = 0.33617, u1 = 0.285192, v1 = 0.442553 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NWE/LegsNWE0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.28702, v0 = 0.33617, u1 = 0.332724, v1 = 0.442553 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NWE/LegsNWE0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.334552, v0 = 0.33617, u1 = 0.380256, v1 = 0.442553 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NWE/LegsNWE0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.382084, v0 = 0.33617, u1 = 0.427788, v1 = 0.442553 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NWN/LegsNWN0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.429616, v0 = 0.33617, u1 = 0.47532, v1 = 0.442553 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NWN/LegsNWN0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.477148, v0 = 0.33617, u1 = 0.522852, v1 = 0.442553 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NWN/LegsNWN0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.52468, v0 = 0.33617, u1 = 0.570384, v1 = 0.442553 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NWN/LegsNWN0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.572212, v0 = 0.33617, u1 = 0.617916, v1 = 0.442553 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NWN/LegsNWN0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.619744, v0 = 0.33617, u1 = 0.665448, v1 = 0.442553 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NWN/LegsNWN0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.667276, v0 = 0.33617, u1 = 0.71298, v1 = 0.442553 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NWS/LegsNWS0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.714808, v0 = 0.33617, u1 = 0.760512, v1 = 0.442553 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NWS/LegsNWS0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.76234, v0 = 0.33617, u1 = 0.808044, v1 = 0.442553 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NWS/LegsNWS0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.809872, v0 = 0.33617, u1 = 0.855576, v1 = 0.442553 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NWS/LegsNWS0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.857404, v0 = 0.33617, u1 = 0.903108, v1 = 0.442553 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NWS/LegsNWS0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.904936, v0 = 0.33617, u1 = 0.95064, v1 = 0.442553 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NWS/LegsNWS0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.952468, v0 = 0.33617, u1 = 0.998172, v1 = 0.442553 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NWW/LegsNWW0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.00182815, v0 = 0.446809, u1 = 0.047532, v1 = 0.553191 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NWW/LegsNWW0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.0493601, v0 = 0.446809, u1 = 0.095064, v1 = 0.553191 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NWW/LegsNWW0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.0968921, v0 = 0.446809, u1 = 0.142596, v1 = 0.553191 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NWW/LegsNWW0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.144424, v0 = 0.446809, u1 = 0.190128, v1 = 0.553191 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NWW/LegsNWW0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.191956, v0 = 0.446809, u1 = 0.23766, v1 = 0.553191 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "NWW/LegsNWW0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.239488, v0 = 0.446809, u1 = 0.285192, v1 = 0.553191 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SE/LegsSE0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.28702, v0 = 0.446809, u1 = 0.332724, v1 = 0.553191 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SE/LegsSE0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.334552, v0 = 0.446809, u1 = 0.380256, v1 = 0.553191 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SE/LegsSE0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.382084, v0 = 0.446809, u1 = 0.427788, v1 = 0.553191 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SE/LegsSE0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.429616, v0 = 0.446809, u1 = 0.47532, v1 = 0.553191 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SE/LegsSE0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.477148, v0 = 0.446809, u1 = 0.522852, v1 = 0.553191 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SE/LegsSE0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.52468, v0 = 0.446809, u1 = 0.570384, v1 = 0.553191 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SEE/LegsSEE0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.572212, v0 = 0.446809, u1 = 0.617916, v1 = 0.553191 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SEE/LegsSEE0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.619744, v0 = 0.446809, u1 = 0.665448, v1 = 0.553191 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SEE/LegsSEE0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.667276, v0 = 0.446809, u1 = 0.71298, v1 = 0.553191 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SEE/LegsSEE0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.714808, v0 = 0.446809, u1 = 0.760512, v1 = 0.553191 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SEE/LegsSEE0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.76234, v0 = 0.446809, u1 = 0.808044, v1 = 0.553191 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SEE/LegsSEE0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.809872, v0 = 0.446809, u1 = 0.855576, v1 = 0.553191 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SEN/LegsSEN0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.857404, v0 = 0.446809, u1 = 0.903108, v1 = 0.553191 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SEN/LegsSEN0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.904936, v0 = 0.446809, u1 = 0.95064, v1 = 0.553191 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SEN/LegsSEN0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.952468, v0 = 0.446809, u1 = 0.998172, v1 = 0.553191 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SEN/LegsSEN0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.00182815, v0 = 0.557447, u1 = 0.047532, v1 = 0.66383 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SEN/LegsSEN0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.0493601, v0 = 0.557447, u1 = 0.095064, v1 = 0.66383 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SEN/LegsSEN0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.0968921, v0 = 0.557447, u1 = 0.142596, v1 = 0.66383 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SES/LegsSES0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.144424, v0 = 0.557447, u1 = 0.190128, v1 = 0.66383 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SES/LegsSES0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.191956, v0 = 0.557447, u1 = 0.23766, v1 = 0.66383 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SES/LegsSES0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.239488, v0 = 0.557447, u1 = 0.285192, v1 = 0.66383 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SES/LegsSES0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.28702, v0 = 0.557447, u1 = 0.332724, v1 = 0.66383 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SES/LegsSES0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.334552, v0 = 0.557447, u1 = 0.380256, v1 = 0.66383 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SES/LegsSES0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.382084, v0 = 0.557447, u1 = 0.427788, v1 = 0.66383 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SEW/LegsSEW0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.429616, v0 = 0.557447, u1 = 0.47532, v1 = 0.66383 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SEW/LegsSEW0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.477148, v0 = 0.557447, u1 = 0.522852, v1 = 0.66383 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SEW/LegsSEW0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.52468, v0 = 0.557447, u1 = 0.570384, v1 = 0.66383 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SEW/LegsSEW0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.572212, v0 = 0.557447, u1 = 0.617916, v1 = 0.66383 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SEW/LegsSEW0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.619744, v0 = 0.557447, u1 = 0.665448, v1 = 0.66383 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SEW/LegsSEW0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.667276, v0 = 0.557447, u1 = 0.71298, v1 = 0.66383 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SN/LegsSN0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.714808, v0 = 0.557447, u1 = 0.760512, v1 = 0.66383 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SN/LegsSN0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.76234, v0 = 0.557447, u1 = 0.808044, v1 = 0.66383 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SN/LegsSN0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.809872, v0 = 0.557447, u1 = 0.855576, v1 = 0.66383 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SN/LegsSN0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.857404, v0 = 0.557447, u1 = 0.903108, v1 = 0.66383 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SN/LegsSN0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.904936, v0 = 0.557447, u1 = 0.95064, v1 = 0.66383 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SN/LegsSN0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.952468, v0 = 0.557447, u1 = 0.998172, v1 = 0.66383 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SS/LegsSS0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.00182815, v0 = 0.668085, u1 = 0.047532, v1 = 0.774468 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SS/LegsSS0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.0493601, v0 = 0.668085, u1 = 0.095064, v1 = 0.774468 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SS/LegsSS0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.0968921, v0 = 0.668085, u1 = 0.142596, v1 = 0.774468 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SS/LegsSS0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.144424, v0 = 0.668085, u1 = 0.190128, v1 = 0.774468 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SS/LegsSS0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.191956, v0 = 0.668085, u1 = 0.23766, v1 = 0.774468 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SS/LegsSS0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.239488, v0 = 0.668085, u1 = 0.285192, v1 = 0.774468 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SW/LegsSW0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.28702, v0 = 0.668085, u1 = 0.332724, v1 = 0.774468 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SW/LegsSW0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.334552, v0 = 0.668085, u1 = 0.380256, v1 = 0.774468 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SW/LegsSW0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.382084, v0 = 0.668085, u1 = 0.427788, v1 = 0.774468 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SW/LegsSW0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.429616, v0 = 0.668085, u1 = 0.47532, v1 = 0.774468 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SW/LegsSW0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.477148, v0 = 0.668085, u1 = 0.522852, v1 = 0.774468 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SW/LegsSW0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.52468, v0 = 0.668085, u1 = 0.570384, v1 = 0.774468 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SWE/LegsSWE0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.572212, v0 = 0.668085, u1 = 0.617916, v1 = 0.774468 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SWE/LegsSWE0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.619744, v0 = 0.668085, u1 = 0.665448, v1 = 0.774468 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SWE/LegsSWE0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.667276, v0 = 0.668085, u1 = 0.71298, v1 = 0.774468 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SWE/LegsSWE0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.714808, v0 = 0.668085, u1 = 0.760512, v1 = 0.774468 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SWE/LegsSWE0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.76234, v0 = 0.668085, u1 = 0.808044, v1 = 0.774468 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SWE/LegsSWE0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.809872, v0 = 0.668085, u1 = 0.855576, v1 = 0.774468 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SWN/LegsSWN0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.857404, v0 = 0.668085, u1 = 0.903108, v1 = 0.774468 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SWN/LegsSWN0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.904936, v0 = 0.668085, u1 = 0.95064, v1 = 0.774468 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SWN/LegsSWN0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.952468, v0 = 0.668085, u1 = 0.998172, v1 = 0.774468 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SWN/LegsSWN0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.00182815, v0 = 0.778723, u1 = 0.047532, v1 = 0.885106 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SWN/LegsSWN0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.0493601, v0 = 0.778723, u1 = 0.095064, v1 = 0.885106 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SWN/LegsSWN0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.0968921, v0 = 0.778723, u1 = 0.142596, v1 = 0.885106 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SWS/LegsSWS0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.144424, v0 = 0.778723, u1 = 0.190128, v1 = 0.885106 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SWS/LegsSWS0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.191956, v0 = 0.778723, u1 = 0.23766, v1 = 0.885106 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SWS/LegsSWS0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.239488, v0 = 0.778723, u1 = 0.285192, v1 = 0.885106 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SWS/LegsSWS0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.28702, v0 = 0.778723, u1 = 0.332724, v1 = 0.885106 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SWS/LegsSWS0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.334552, v0 = 0.778723, u1 = 0.380256, v1 = 0.885106 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SWS/LegsSWS0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.382084, v0 = 0.778723, u1 = 0.427788, v1 = 0.885106 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SWW/LegsSWW0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.429616, v0 = 0.778723, u1 = 0.47532, v1 = 0.885106 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SWW/LegsSWW0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.477148, v0 = 0.778723, u1 = 0.522852, v1 = 0.885106 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SWW/LegsSWW0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.52468, v0 = 0.778723, u1 = 0.570384, v1 = 0.885106 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SWW/LegsSWW0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.572212, v0 = 0.778723, u1 = 0.617916, v1 = 0.885106 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SWW/LegsSWW0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.619744, v0 = 0.778723, u1 = 0.665448, v1 = 0.885106 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "SWW/LegsSWW0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.667276, v0 = 0.778723, u1 = 0.71298, v1 = 0.885106 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "WE/LegsWE0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.714808, v0 = 0.778723, u1 = 0.760512, v1 = 0.885106 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "WE/LegsWE0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.76234, v0 = 0.778723, u1 = 0.808044, v1 = 0.885106 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "WE/LegsWE0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.809872, v0 = 0.778723, u1 = 0.855576, v1 = 0.885106 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "WE/LegsWE0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.857404, v0 = 0.778723, u1 = 0.903108, v1 = 0.885106 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "WE/LegsWE0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.904936, v0 = 0.778723, u1 = 0.95064, v1 = 0.885106 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "WE/LegsWE0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.952468, v0 = 0.778723, u1 = 0.998172, v1 = 0.885106 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "WN/LegsWN0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.00182815, v0 = 0.889362, u1 = 0.047532, v1 = 0.995745 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "WN/LegsWN0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.0493601, v0 = 0.889362, u1 = 0.095064, v1 = 0.995745 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "WN/LegsWN0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.0968921, v0 = 0.889362, u1 = 0.142596, v1 = 0.995745 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "WN/LegsWN0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.144424, v0 = 0.889362, u1 = 0.190128, v1 = 0.995745 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "WN/LegsWN0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.191956, v0 = 0.889362, u1 = 0.23766, v1 = 0.995745 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "WN/LegsWN0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.239488, v0 = 0.889362, u1 = 0.285192, v1 = 0.995745 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "WS/LegsWS0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.28702, v0 = 0.889362, u1 = 0.332724, v1 = 0.995745 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "WS/LegsWS0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.334552, v0 = 0.889362, u1 = 0.380256, v1 = 0.995745 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "WS/LegsWS0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.382084, v0 = 0.889362, u1 = 0.427788, v1 = 0.995745 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "WS/LegsWS0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.429616, v0 = 0.889362, u1 = 0.47532, v1 = 0.995745 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "WS/LegsWS0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.477148, v0 = 0.889362, u1 = 0.522852, v1 = 0.995745 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "WS/LegsWS0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.52468, v0 = 0.889362, u1 = 0.570384, v1 = 0.995745 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "WW/LegsEW0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.572212, v0 = 0.889362, u1 = 0.617916, v1 = 0.995745 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "WW/LegsEW0001",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.619744, v0 = 0.889362, u1 = 0.665448, v1 = 0.995745 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "WW/LegsEW0002",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.667276, v0 = 0.889362, u1 = 0.71298, v1 = 0.995745 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "WW/LegsEW0003",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.714808, v0 = 0.889362, u1 = 0.760512, v1 = 0.995745 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "WW/LegsEW0004",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.76234, v0 = 0.889362, u1 = 0.808044, v1 = 0.995745 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "WW/LegsEW0005",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.809872, v0 = 0.889362, u1 = 0.855576, v1 = 0.995745 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "idle/LegsEE0000",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.00182815, v0 = 0.00425532, u1 = 0.047532, v1 = 0.110638 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

