-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:7bd83a462a9a370bf29ffacbeba08cd1:e63569817150ce2520cba791fd56667b:71416770a0f30437e792b92b83faccc1$
-- 

return {
	texture = 'shuruken.png',
	frames = {
			{
				name = "Shuruken1.png",
				spriteColorRect = { x = 0, y = 0, width = 25, height = 25 },
				uvRect = { u0 = 0.517857, v0 = 0.0689655, u1 = 0.964286, v1 = 0.931035 },
				spriteSourceSize = { width = 25, height = 25 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Shuruken2.png",
				spriteColorRect = { x = 0, y = 0, width = 25, height = 25 },
				uvRect = { u0 = 0.0357143, v0 = 0.0689655, u1 = 0.482143, v1 = 0.931035 },
				spriteSourceSize = { width = 25, height = 25 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

