-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:5790f75d9ea7a25e52a5f581a0ba1991:4eee7b1d00944bde4b8adfef254da1e0:68be5cd994ad61b8675e00e7d377abbb$
-- 

return {
	texture = 'zombie.png',
	frames = {
			{
				name = "idle/Bum10000",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 54 },
				uvRect = { u0 = 0.00735294, v0 = 0.0344828, u1 = 0.165441, v1 = 0.965517 },
				spriteSourceSize = { width = 43, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "walk/Bum10000",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 54 },
				uvRect = { u0 = 0.00735294, v0 = 0.0344828, u1 = 0.165441, v1 = 0.965517 },
				spriteSourceSize = { width = 43, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "walk/Bum10001",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 54 },
				uvRect = { u0 = 0.172794, v0 = 0.0344828, u1 = 0.330882, v1 = 0.965517 },
				spriteSourceSize = { width = 43, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "walk/Bum10002",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 54 },
				uvRect = { u0 = 0.338235, v0 = 0.0344828, u1 = 0.496324, v1 = 0.965517 },
				spriteSourceSize = { width = 43, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "walk/Bum10003",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 54 },
				uvRect = { u0 = 0.503676, v0 = 0.0344828, u1 = 0.661765, v1 = 0.965517 },
				spriteSourceSize = { width = 43, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "walk/Bum10004",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 54 },
				uvRect = { u0 = 0.669118, v0 = 0.0344828, u1 = 0.827206, v1 = 0.965517 },
				spriteSourceSize = { width = 43, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "walk/Bum10005",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 54 },
				uvRect = { u0 = 0.834559, v0 = 0.0344828, u1 = 0.992647, v1 = 0.965517 },
				spriteSourceSize = { width = 43, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

