-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:83f658fad5aaeaa459026c938ee9332d:126124a4247abc5cb58ee5d1993f3536:d34906d72d6452af0a48e8f2a27a488b$
-- 

return {
	texture = 'zombie.png',
	frames = {
			{
				name = "Zombie_Base.png",
				spriteColorRect = { x = 10, y = 10, width = 30, height = 38 },
				uvRect = { u0 = 0.692308, v0 = 0.04, u1 = 0.980769, v1 = 0.8 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Zombie_Charge.png",
				spriteColorRect = { x = 3, y = 11, width = 46, height = 36 },
				uvRect = { u0 = 0.0192308, v0 = 0.04, u1 = 0.365385, v1 = 0.96 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Zombie_Drinking.png",
				spriteColorRect = { x = 10, y = 3, width = 30, height = 46 },
				uvRect = { u0 = 0.384615, v0 = 0.04, u1 = 0.673077, v1 = 0.96 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}

