PC_BASE_SPEED = 120.0
PC_BULLET_SPEED = 600.0
BUM_BASE_SPEED = 80.0
NINJA_BASE_SPEED = 150.0
NINJA_STAR_SPEED = 180.0

PC_BULLET_DAMAGE = 5
BUM_HEALTH = 10
NINJA_HEALTH = 20

-- in seconds
PC_FIRE_DELAY = 0.25

-- sides of a die
SPEEDBOOST_SIDES = 4

-- in seconds
SPEEDBOOST_DURATION = 5
DAMAGEBOOST_DURATION = 5

SPEEDBOOST_MULTIPLIER = 1.75
DAMAGEBOOST_DAMAGE_MULTIPLIER = 1
DAMAGEBOOST_RATE_MULTIPLIER = 2

JUNKYARD_RANDOMNESS = 2
JUNKYARD_DELAY = 1.2 -- seconds

-- don't change these
COL_PC = 0x01
COL_PC_BULLET = 0x02
COL_ENEMY = 0x04
COL_WALL = 0x10
COL_PICKUP = 0x20
COL_ENEMY_BULLET = 0x40
